---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
#      - ruby
#      - python
#      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
#  markdownlint:
#    enabled: true
ratings:
  paths:
#  - "**.inc"
  - "**.js"
  - "**.jsx"
#  - "**.module"
#  - "**.php"
#  - "**.py"
#  - "**.rb"
#  - "**.md"
exclude_paths:
- test/
